contact_links:
  - name: Rebase Suggestions
    url: https://github.com/VENUS-Station/V.E.N.U.S-tg/discussions
    about: Post suggestions or tweak requests for us to look through while the rebase process is ongoing. This section will be used until we officially rebase.
  - name: Suggestions and Suggestion bounties
    url: https://discord.gg/kCuWJRdzb7
    about: Post suggestions for us to apply onto our station, which could be considered for the suggestions bounty system.
