name: Report Issue to Upstream

on:
  issue_comment:
    types: [created]

jobs:
  report-upstream:
    if: github.event.issue.pull_request == null && startsWith(github.event.comment.body, '/report_upstream')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Report to upstream
        uses: actions/github-script@v7
        with:
          script: |
            const { reportUpstream } = await import('${{ github.workspace }}/tools/issue_hooks/reportUpstream.js');
            await reportUpstream({ github, context });
